
from customtkinter import *
from PIL import Image

class Root(CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.FRAME4 = CTkFrame(master=self, height=234, width=273, fg_color="transparent")
        self.FRAME4.pack_propagate(False)
        self.FRAME4.pack(padx=(0, 0), anchor="center", expand=0, fill="y", ipadx=0, ipady=0, pady=10, side="left")
        self.LABEL6 = CTkLabel(master=self.FRAME4, text="Custom Tkinter\nBuilder", image=CTkImage(Image.open("Assets/outline_logo_dev_white_36dp_2x.png"), size=(72, 72)), compound="left", justify="left", text_color=("gray10", "#f1f0ea"), font=CTkFont(family="SF Display", size=21))
        self.LABEL6.pack(padx=(1, 1), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, pady=(15, 0), side="top")
        self.project_btn = CTkButton(master=self.FRAME4, text="      Projects", corner_radius=0, anchor="w", height=45, fg_color=("#cf245e", "#cf245e"), hover_color=("#ae1d4f", "#ae1e4f"), text_color=("gray98", "#f1f0ea"), font=CTkFont(family="SF Display", size=20))
        self.project_btn.pack(pady=(29, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.customize_btn = CTkButton(master=self.FRAME4, text="      Customize", corner_radius=0, anchor="w", height=45, fg_color="transparent", hover_color=("#ae1d4f", "#ae1e4f"), text_color=("#0d0c1d", "#f1f0ea"), font=CTkFont(family="SF Display", size=20))
        self.customize_btn.pack(pady=(0, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.FRAME6_copy = CTkFrame(master=self, height=234, width=273, fg_color=("#dfddcf", "#151a33"))
        self.FRAME6_copy.pack_propagate(False)
        self.FRAME6_copy.pack(expand="true", anchor="center", fill="both", ipadx=0, ipady=0, padx=(0, 10), pady=10, side="left")
        self.FRAME9 = CTkFrame(master=self.FRAME6_copy, fg_color="transparent", height=61)
        self.FRAME9.pack_propagate(False)
        self.FRAME9.pack(pady=(5, 5), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=5, side="top")
        self.FRAME10 = CTkFrame(master=self.FRAME9, height=42, fg_color=("#dfddcf", "#151a33"))
        self.FRAME10.pack_propagate(False)
        self.FRAME10.pack(padx=(15, 1), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL11 = CTkLabel(master=self.FRAME10, text="search", text_color=("gray10", "#f0f0e9"), font=CTkFont(family="Material Icons Outlined", size=25))
        self.LABEL11.pack(side="left", anchor="center", expand=0, fill="none", ipadx=0, ipady=0, padx=0, pady=0)
        self.search_entry = CTkEntry(master=self.FRAME10, placeholder_text="Search Projects", border_width=0, fg_color=("#dfddcf", "#151a33"), placeholder_text_color=("#14122d", "#dfddcf"), text_color=("#0d0c1d", "#f0f0e9"), font=CTkFont(family="SF Display", size=14))
        self.search_entry.pack(padx=(0, 4), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=0, side="left")
        self.BUTTON15_copy = CTkButton(master=self.FRAME9, text="Open", corner_radius=2, fg_color=("#cf245e", "#cf245e"), hover_color=("#ae1d4f", "#ae1d4f"), width=95, font=CTkFont(family="SF Display", size=14))
        self.BUTTON15_copy.pack(padx=(20, 16), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="right")
        self.BUTTON13 = CTkButton(master=self.FRAME9, text="New Project", corner_radius=2, fg_color=("#cf245e", "#cf245e"), hover_color=("#ae1d4f", "#ae1d4f"), font=CTkFont(family="SF Display", size=14))
        self.BUTTON13.pack(padx=(0, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="right")
        self.FRAME15 = CTkFrame(master=self.FRAME6_copy, fg_color="transparent")
        self.FRAME15.pack_propagate(False)
        self.FRAME15.pack(pady=(0, 20), anchor="center", expand=1, fill="both", ipadx=0, ipady=0, padx=20, side="top")
        self.project_frame = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.project_frame.pack_propagate(False)
        self.project_frame.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL17 = CTkLabel(master=self.project_frame, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL17.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME18 = CTkFrame(master=self.project_frame, height=41, fg_color="transparent")
        self.FRAME18.pack_propagate(False)
        self.FRAME18.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL19 = CTkLabel(master=self.FRAME18, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL19.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL21_copy = CTkLabel(master=self.FRAME18, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL21_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME62_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME62_copy.pack_propagate(False)
        self.FRAME62_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL63_copy = CTkLabel(master=self.FRAME62_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL63_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME64_copy = CTkFrame(master=self.FRAME62_copy, height=41, fg_color="transparent")
        self.FRAME64_copy.pack_propagate(False)
        self.FRAME64_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL65_copy = CTkLabel(master=self.FRAME64_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL65_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL66_copy = CTkLabel(master=self.FRAME64_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL66_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME67_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME67_copy.pack_propagate(False)
        self.FRAME67_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL68_copy = CTkLabel(master=self.FRAME67_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL68_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME69_copy = CTkFrame(master=self.FRAME67_copy, height=41, fg_color="transparent")
        self.FRAME69_copy.pack_propagate(False)
        self.FRAME69_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL70_copy = CTkLabel(master=self.FRAME69_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL70_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL71_copy = CTkLabel(master=self.FRAME69_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL71_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME72_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME72_copy.pack_propagate(False)
        self.FRAME72_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL73_copy = CTkLabel(master=self.FRAME72_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL73_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME74_copy = CTkFrame(master=self.FRAME72_copy, height=41, fg_color="transparent")
        self.FRAME74_copy.pack_propagate(False)
        self.FRAME74_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL75_copy = CTkLabel(master=self.FRAME74_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL75_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL76_copy = CTkLabel(master=self.FRAME74_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL76_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME77_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME77_copy.pack_propagate(False)
        self.FRAME77_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL78_copy = CTkLabel(master=self.FRAME77_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL78_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME79_copy = CTkFrame(master=self.FRAME77_copy, height=41, fg_color="transparent")
        self.FRAME79_copy.pack_propagate(False)
        self.FRAME79_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL80_copy = CTkLabel(master=self.FRAME79_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL80_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL81_copy = CTkLabel(master=self.FRAME79_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL81_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME82_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME82_copy.pack_propagate(False)
        self.FRAME82_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL83_copy = CTkLabel(master=self.FRAME82_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL83_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME84_copy = CTkFrame(master=self.FRAME82_copy, height=41, fg_color="transparent")
        self.FRAME84_copy.pack_propagate(False)
        self.FRAME84_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL85_copy = CTkLabel(master=self.FRAME84_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL85_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL86_copy = CTkLabel(master=self.FRAME84_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL86_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME87_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME87_copy.pack_propagate(False)
        self.FRAME87_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL88_copy = CTkLabel(master=self.FRAME87_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL88_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME89_copy = CTkFrame(master=self.FRAME87_copy, height=41, fg_color="transparent")
        self.FRAME89_copy.pack_propagate(False)
        self.FRAME89_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL90_copy = CTkLabel(master=self.FRAME89_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL90_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL91_copy = CTkLabel(master=self.FRAME89_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL91_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.FRAME92_copy = CTkFrame(master=self.FRAME15, height=64, fg_color="transparent")
        self.FRAME92_copy.pack_propagate(False)
        self.FRAME92_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        self.LABEL93_copy = CTkLabel(master=self.FRAME92_copy, text="CT", width=35, height=35, fg_color=("#cf245e", "#cf245e"), corner_radius=3, text_color=("#dfddcf", "#f0f0e9"), font=CTkFont(family="SF Display"))
        self.LABEL93_copy.pack(padx=(15, 0), anchor="center", expand=0, fill="none", ipadx=0, ipady=0, pady=0, side="left")
        self.FRAME94_copy = CTkFrame(master=self.FRAME92_copy, height=41, fg_color="transparent")
        self.FRAME94_copy.pack_propagate(False)
        self.FRAME94_copy.pack(padx=(25, 1), anchor="center", expand=1, fill="x", ipadx=0, ipady=0, pady=1, side="left")
        self.LABEL95_copy = CTkLabel(master=self.FRAME94_copy, text="CustomTkinterBuilder", anchor="w", text_color=("gray10", "#f0f0e9"), height=8, font=CTkFont(family="SF Display", size=14))
        self.LABEL95_copy.pack(pady=(1, 0), anchor="center", expand=0, fill="x", ipadx=0, ipady=0, padx=0, side="top")
        self.LABEL96_copy = CTkLabel(master=self.FRAME94_copy, text="~/CustomTkinterBuilder", anchor="w", text_color=("gray10", "#9d9d99"), height=15, font=CTkFont(family="SF Display", size=14))
        self.LABEL96_copy.pack(fill="x", anchor="center", expand=0, ipadx=0, ipady=0, padx=0, pady=0, side="top")
        
set_default_color_theme("green")
app = Root()
app.geometry("1000x600")
app.title("Welcome to Custom Tkinter Builder")
app.configure(fg_color=["#F1F0EA", "#0D0C1D"])
app.mainloop()
            
